apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system # todo gопробовать поменять
  name: config
data:
  config: |
    address-pools:
    - name: services
      protocol: layer2
      addresses
      - 192.168.99.100-192.168.99.100